DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user LOGIN PASSWORD 'app_password';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'webhook_readonly') THEN
    CREATE ROLE webhook_readonly NOLOGIN;
  END IF;
END $$;

GRANT ALL PRIVILEGES ON SCHEMA public TO app_user;
GRANT USAGE, CREATE ON SCHEMA public TO app_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO app_user;