DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user LOGIN PASSWORD 'app_password!';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'webhook_readonly') THEN
    CREATE ROLE webhook_readonly NOLOGIN;
  END IF;
END $$;

GRANT USAGE, CREATE ON SCHEMA public TO app_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app_user;

GRANT USAGE ON SCHEMA public TO webhook_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO webhook_readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT SELECT ON TABLES TO webhook_readonly;